version: '3.5'

volumes:
  appnet:
    driver: local

services:

  postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_USER=guest
      - POSTGRES_PASSWORD=guest
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - appnet:/var/lib/rabbitmq/data

  user-api:
    build:
      context: .
      dockerfile: UserApi\Dockerfile
    image: user-api
    container_name: user-api
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RABBIT_HOST=rabbitmq
      - RABBIT_HOST_VIRTUAL_HOST=/
      - RABBIT_USERNAME=guest
      - RABBIT_PASSWORD=guest
    restart: on-failure
    depends_on:
      - rabbitmq
    volumes:
      - ./api:/user/src/app/

  organization-api:
    build:
      context: .
      dockerfile: OrganizationApi\Dockerfile
    image: organization-api
    container_name: organization-api
    ports:
      - 5001:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - RABBIT_HOST=rabbitmq
      - RABBIT_HOST_VIRTUAL_HOST=/
      - RABBIT_USERNAME=guest
      - RABBIT_PASSWORD=guest
      - PSQL_CONNECTION_STRING=User ID=guest;Password=guest;Host=postgresql;Port=5432;Database=user_api;Pooling=true;
    restart: on-failure
    depends_on:
      - rabbitmq
      - postgresql
    volumes:
      - ./api:/organization/src/app/